name: "release"

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    RELEASE_BODY_ARTIFACT: release-body
    RELEASE_BODY_ARTIFACT_PATH: release-body.txt
    RELEASE_BODY_ARCHIVE_ARTIFACT: release-body-archive
    WINDOWS_X86_64_ARTIFACT: windows-x86_64
    WINDOWS_X86_64_ARTIFACT_PATH: windows-x86_64.txt
    WINDOWS_X86_64_ARCHIVE_ARTIFACT: windows-x86_64-archive
    WINDOWS_X86_64_DEBUG_ARTIFACT: windows-x86_64-debug
    WINDOWS_X86_64_DEBUG_ARTIFACT_PATH: windows-x86_64-debug.txt
    WINDOWS_X86_64_DEBUG_ARCHIVE_ARTIFACT: windows-x86_64-debug-archive
    WINDOWS_X86_32_ARTIFACT: windows-x86_32
    WINDOWS_X86_32_ARTIFACT_PATH: windows-x86_32.txt
    WINDOWS_X86_32_ARCHIVE_ARTIFACT: windows-x86_32-archive
    WINDOWS_X86_32_DEBUG_ARTIFACT: windows-x86_32-debug
    WINDOWS_X86_32_DEBUG_ARTIFACT_PATH: windows-x86_32-debug.txt
    WINDOWS_X86_32_DEBUG_ARCHIVE_ARTIFACT: windows-x86_32-debug-archive
    LINUX_SDL2_X86_64_ARTIFACT: linux-sdl2-x86_64
    LINUX_SDL2_X86_64_ARTIFACT_PATH: linux-sdl2-x86_64.txt
    LINUX_SDL2_X86_64_ARCHIVE_ARTIFACT: linux-sdl2-x86_64-archive
    LINUX_SDL1_X86_64_ARTIFACT: linux-sdl1-x86_64
    LINUX_SDL1_X86_64_ARTIFACT_PATH: linux-sdl1-x86_64.txt
    LINUX_SDL1_X86_64_ARCHIVE_ARTIFACT: linux-sdl1-x86_64-archive

jobs:
  create_release_body:
    name: Create release body
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: create_release_body_archive
        run: |
          archive_file="${{ env.RELEASE_BODY_ARTIFACT }}.md"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          echo "### Release ${{ github.ref_name }}" > ${archive_file}
          echo "" >> ${archive_file}
          prev_tag=$(git tag --sort=-creatordate | grep -v "^${{ github.ref_name }}$" | head -n1)
          if [ -n "$prev_tag" ]; then
            echo "### Changes since ${prev_tag}" >> ${archive_file}
            git log --pretty=format:"%s (%an)" "${prev_tag}..${{ github.sha }}" | awk '{print "• " $0}' >> ${archive_file}
          else
            echo "### Initial release" >> ${archive_file}
          fi

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_release_body_archive.outputs.archive_file }}' > $RELEASE_BODY_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_BODY_ARTIFACT }}
          path: ${{ env.RELEASE_BODY_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_BODY_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_release_body_archive.outputs.archive_file }}
          retention-days: 1

  build_windows_x86_64:
    name: Build (Windows x86_64)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: msys2-devel base-devel binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-nasm zip wget
          msystem: MINGW64

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_windows_x86_64_archive
        run: |
          make -j$(nproc) mingw BUILD_X64_EXE=1 SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="${{ env.WINDOWS_X86_64_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo64.exe src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_windows_x86_64_archive.outputs.archive_file }}' > $WINDOWS_X86_64_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARTIFACT }}
          path: ${{ env.WINDOWS_X86_64_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_windows_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  build_windows_x86_64_debug:
    name: Build (Windows x86_64 Debug)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: msys2-devel base-devel binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-nasm zip wget
          msystem: MINGW64

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_windows_x86_64_debug_archive
        run: |
          make -j$(nproc) mingw BUILD_X64_EXE=1 SKIPDEPEND=1
          archive_file="${{ env.WINDOWS_X86_64_DEBUG_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo64d.exe src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_windows_x86_64_debug_archive.outputs.archive_file }}' > $WINDOWS_X86_64_DEBUG_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_DEBUG_ARTIFACT }}
          path: ${{ env.WINDOWS_X86_64_DEBUG_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_DEBUG_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_windows_x86_64_debug_archive.outputs.archive_file }}
          retention-days: 1

  build_windows_x86_32:
    name: Build (Windows x86_32)
    runs-on: windows-latest
    continue-on-error: true
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: msys2-devel base-devel binutils mingw-w64-i686-toolchain mingw-w64-i686-nasm zip wget
          msystem: MINGW32

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_windows_x86_32_archive
        run: |
          make -j$(nproc) mingw SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="${{ env.WINDOWS_X86_32_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo.exe src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_windows_x86_32_archive.outputs.archive_file }}' > $WINDOWS_X86_32_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_ARTIFACT }}
          path: ${{ env.WINDOWS_X86_32_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_windows_x86_32_archive.outputs.archive_file }}
          retention-days: 1

  build_windows_x86_32_debug:
    name: Build (Windows x86_32 Debug)
    runs-on: windows-latest
    continue-on-error: true
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: msys2-devel base-devel binutils mingw-w64-i686-toolchain mingw-w64-i686-nasm zip wget
          msystem: MINGW32

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_windows_x86_32_debug_archive
        run: |
          make -j$(nproc) mingw SKIPDEPEND=1
          archive_file="${{ env.WINDOWS_X86_32_DEBUG_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneod.exe src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_windows_x86_32_debug_archive.outputs.archive_file }}' > $WINDOWS_X86_32_DEBUG_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_DEBUG_ARTIFACT }}
          path: ${{ env.WINDOWS_X86_32_DEBUG_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_DEBUG_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_windows_x86_32_debug_archive.outputs.archive_file }}
          retention-days: 1

  build_linux_sdl2_x86_64:
    name: Build (Linux SDL2 x86_64)
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsdl2-dev libsdl2-image-dev

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_linux_sdl2_x86_64_archive
        run: |
          make -j$(nproc) sdl2 SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="${{ env.LINUX_SDL2_X86_64_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_linux_sdl2_x86_64_archive.outputs.archive_file }}' > $LINUX_SDL2_X86_64_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARTIFACT }}
          path: ${{ env.LINUX_SDL2_X86_64_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_linux_sdl2_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  build_linux_sdl1_x86_64:
    name: Build (Linux SDL1 x86_64)
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsdl1.2-dev

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_linux_sdl1_x86_64_archive
        run: |
          make -j$(nproc) sdl SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="${{ env.LINUX_SDL1_X86_64_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_linux_sdl1_x86_64_archive.outputs.archive_file }}' > $LINUX_SDL1_X86_64_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARTIFACT }}
          path: ${{ env.LINUX_SDL1_X86_64_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_linux_sdl1_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  release:
    needs: [ create_release_body, build_windows_x86_64, build_windows_x86_64_debug, build_windows_x86_32, build_windows_x86_32_debug, build_linux_sdl2_x86_64, build_linux_sdl1_x86_64 ]
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Release body
      - name: Download Artifact (Release body)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.RELEASE_BODY_ARTIFACT }}

      - name: Extract Archive Path (Release body) and Store in Step Outputs
        id: store_release_body
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $RELEASE_BODY_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Release body)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.RELEASE_BODY_ARCHIVE_ARTIFACT }}

      # Windows x86_64
      - name: Download Artifact (Windows x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARTIFACT }}

      - name: Extract Archive Path (Windows x86_64) and Store in Step Outputs
        id: store_windows_x86_64
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $WINDOWS_X86_64_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Windows x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARCHIVE_ARTIFACT }}

      # Windows x86_64 Debug
      - name: Download Artifact (Windows x86_64 Debug)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_DEBUG_ARTIFACT }}

      - name: Extract Archive Path (Windows x86_64 Debug) and Store in Step Outputs
        id: store_windows_x86_64_debug
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $WINDOWS_X86_64_DEBUG_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Windows x86_64 Debug)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_DEBUG_ARCHIVE_ARTIFACT }}

      # Windows x86_32
      - name: Download Artifact (Windows x86_32)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_ARTIFACT }}

      - name: Extract Archive Path (Windows x86_32) and Store in Step Outputs
        id: store_windows_x86_32
        continue-on-error: true
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $WINDOWS_X86_32_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Windows x86_32)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_ARCHIVE_ARTIFACT }}

      # Windows x86_32 Debug
      - name: Download Artifact (Windows x86_32 Debug)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_DEBUG_ARTIFACT }}

      - name: Extract Archive Path (Windows x86_32 Debug) and Store in Step Outputs
        id: store_windows_x86_32_debug
        continue-on-error: true
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $WINDOWS_X86_32_DEBUG_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Windows x86_32 Debug)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_32_DEBUG_ARCHIVE_ARTIFACT }}

      # Linux SDL2 x86_64
      - name: Download Artifact (Linux SDL2 x86_64)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARTIFACT }}

      - name: Extract Archive Path (Linux SDL2 x86_64) and Store in Step Outputs
        id: store_linux_sdl2_x86_64
        continue-on-error: true
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $LINUX_SDL2_X86_64_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Linux SDL2 x86_64)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARCHIVE_ARTIFACT }}

      # Linux SDL1 x86_64
      - name: Download Artifact (Linux SDL1 x86_64)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARTIFACT }}

      - name: Extract Archive Path (Linux SDL1 x86_64) and Store in Step Outputs
        id: store_linux_sdl1_x86_64
        continue-on-error: true
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $LINUX_SDL1_X86_64_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Linux SDL1 x86_64)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARCHIVE_ARTIFACT }}

      # Create versioned release
      - name: Create versioned release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "FinalBurn Neo ${{ github.ref_name }}" \
            --latest \
            --target "${{ github.sha }}" \
            --notes-file "${{ steps.store_release_body.outputs.archive_path }}" \
            ${{ steps.store_linux_sdl2_x86_64.outputs.archive_path }} \
            ${{ steps.store_linux_sdl1_x86_64.outputs.archive_path }} \
            ${{ steps.store_windows_x86_64.outputs.archive_path }} \
            ${{ steps.store_windows_x86_32.outputs.archive_path }} \
            ${{ steps.store_windows_x86_64_debug.outputs.archive_path }} \
            ${{ steps.store_windows_x86_32_debug.outputs.archive_path }}
